version: '3'

services:
  envoy-npm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: envoy-npm
    restart: unless-stopped
    environment:
      - NPM_API_URL=${NPM_API_URL:-http://npm:81}
      - NPM_API_EMAIL=${NPM_API_EMAIL:-admin@example.com}
      - NPM_API_PASSWORD=${NPM_API_PASSWORD:-changeme}
      - DOCKER_SOCKET=${DOCKER_SOCKET:-/var/run/docker.sock}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - RETRY_DELAY=${RETRY_DELAY:-5}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-3600}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: ${NPM_NETWORK:-npm_network}
